ARG NODE_VERSION=24.7.0-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    curl \
    libc6-compat

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 3003

CMD ["npm", "run", "dev"]